# Generated by Django 5.0.2 on 2024-07-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0002_customuser_accountname_customuser_accountnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='maritalStatus',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=50, null=True),
        ),
    ]
